version: "3.7"

services:
  ui:
    image: docker-arender.packages.nuxeo.com/nuxeo/arender-ui:${VERSION}
    mem_limit: 2g # Copied from Genus example, not sure it's needed
    container_name: ui
    environment:
      - "ARENDERSRV_ARENDER_SERVER_RENDITION_HOSTS=http://dsb-service:8761/"
      - "ARENDERSRV_NUXEO_SERVER_URL=http://localhost:8080"
      - "ARENDERSRV_NUXEO_SERVER_ARENDER_SECRET=OAUTH2_SECRET" # must match nuxeo.conf
    ports:
      - 8081:8080

  service-broker:
    image: docker-arender.packages.nuxeo.com/nuxeo/arender-document-service-broker:${VERSION}
    container_name: dsb-service
    environment:
      - "DSB_KUBEPROVIDER_KUBE.HOSTS_DCV-SERVICE=19999"
      - "DSB_KUBEPROVIDER_KUBE.HOSTS_DRN-SERVICE=9091"
      - "DSB_KUBEPROVIDER_KUBE.HOSTS_DTH-SERVICE=8899"
    ports:
      - 8761:8761
    volumes:
      - arender-tmp:/arender/tmp

  document-renderer:
    image: docker-arender.packages.nuxeo.com/nuxeo/arender-document-renderer:${VERSION}
    container_name: drn-service
    environment:
      - "DRN_EUREKA_INSTANCE_METADATA.MAP_HOST.NAME=drn-service"
      - "DRN_EUREKA_INSTANCE_HOSTNAME=dsb-service"
      - "DRN_EUREKA_SERVER_PORT=8761"
    ports:
      - 9091:9091
    volumes:
      - arender-tmp:/arender/tmp

  document-text-handler:
    image: docker-arender.packages.nuxeo.com/nuxeo/arender-document-text-handler:${VERSION}
    container_name: dth-service
    environment:
      - "DTH_EUREKA_INSTANCE_METADATA.MAP_HOST.NAME=dth-service"
      - "DTH_EUREKA_INSTANCE_HOSTNAME=dsb-service"
      - "DTH_EUREKA_SERVER_PORT=8761"
    ports:
      - 8899:8899
    volumes:
      - arender-tmp:/arender/tmp

  document-converter:
    image: docker-arender.packages.nuxeo.com/nuxeo/arender-document-converter:${VERSION}
    container_name: dcv-service
    environment:
      - "DCV_EUREKA_INSTANCE_METADATA.MAP_HOST.NAME=dcv-service"
      - "DCV_APP_EUREKA_HOSTNAME=dsb-service"
      - "DCV_APP_EUREKA_PORT=8761"
    ports:
      - 19999:19999
    volumes:
      - arender-tmp:/arender/tmp

# Shared temporary folder
volumes:
  arender-tmp:
